### ISSUE TITLE
0.1.0-alpha.3 Checklist

### ISSUE THREAD

**Issue by vector-of-bool** [vector-of-bool/dds#23]
Tasks that need completion for 0.1.0-alpha.3 release:

- [x] Write a changelog
- [x] Publish new docs to vector-of-bool.github.io
- [x] Publish new FreeBSD build
- [x] Update PMM to reference new binaries
- [x] Create new bootstrapping checkpoint for json5 changes
- [x] Update version numbers and references
